# Video source and output
SOURCE_VIDEO_PATH: "input/test_10sec.mp4"
OUTPUT_DIR: "output"

# Model paths
PLAYER_DETECTION_MODEL: "models/player_detect/weights/best.pt"
FIELD_DETECTION_MODEL: "models/last_400.pt"
TEAM_CLASSIFIER_MODEL: "models/team_classifier.pkl"

# Detection parameters
BALL_ID: 0
GOALKEEPER_ID: 1
PLAYER_ID: 2
REFEREE_ID: 3
BATCH_SIZE: 8  # Process 8 frames at a time
FIELD_DETECTION_INTERVAL: 5  # Detect field every 5 frames
CHANGE_THRESHOLD: 0.15  # If frame difference exceeds this, force field detection
MAP_PITCH: false  # Flag to enable pitch mapping visualization

# Processing
DEVICE: "cuda"  # Device to use for inference (cuda or cpu)

# Video output settings
VIDEO_CODEC: "XVID"  # Try with XVID first, fallback to MJPG or 0
VIDEO_EXTENSION: "avi"